### PR TITLE
Export NewLogrAdapter

### PR DESCRIPTION
**Pull request by therealmitchconnors**
I'd like to use this for building controllers which use logr, but not klog.

### CODE REVIEW

**Comment by douglas-reid** [comment]
I don't see a big issue with this PR. That being said, what are the tradeofss vs. having a Config option to opt-out of klog ?

**Comment by therealmitchconnors** [comment]
> I don't see a big issue with this PR. That being said, what are the tradeofss vs. having a Config option to opt-out of klog ?

I'm not sure.  To be clear, this function is only currently used for configuring klog, and this PR allows us to use it for things other than klog.  It has no affect on the current klog use cases.

**Comment by howardjohn** [comment]
SGTM if Doug has no concerns

**Review by howardjohn — APPROVED** [review]
@douglas-reid Feel free to remove hold once your concerns are addressed

**Review by mandarjog — APPROVED** [review]
lgtm. Just exposing existing methods.

**Review by douglas-reid — APPROVED** [review]

**Pull request merged**
