### PR TITLE
Pipe klog/v2 output through standard logging

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/26953

### CODE REVIEW

**Comment by ostromart** [comment]
why do we want to support another logging api rather than consolidating to scope?

**Comment by howardjohn** [comment]
@ostromart this is not about supporting another logging API for consumers of pkg/log. The stuff is all private. The key code is `klog.SetLogger(newLogrAdapter(KlogScope))`. Without this, kubernetes logging goes through its own logging system which makes istioctl print out *tons* of logs and not respect our logging options or formats. This makes it so we pipe the output into zap.

Previously, with klog v1 we had a fork in istio/klog. The proper way of doing this, per the klog docs, is to use SetLogger. SetLogger takes a logr.Logger interface, which is a standard interface for logging (without an implementation). There is a zap logr implementation but it also doesn't respect "Scope", since we invented our own thing, so I had to make our own.

**Comment by ostromart** [comment]
ok, could you add a few more notes about why this is needed and how it's meant to be used? without that it's very hard to know what this is for and why the logging threshold is 3.

**Comment by howardjohn** [comment]
@ostromart added docs about what I commented

**Review by ostromart — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Pull request merged**
