### PR TITLE
Add CurrentValue method for non-dimensional metrics

### PR DESCRIPTION
**Pull request by pitlv2109**
Add CurrentValue method for non-dimensional metrics. Only support Sum and LastValue type.

### CODE REVIEW

**Comment by pitlv2109** [comment]
`Blocked due to plan-no-credits-available Please purchase a new credit block then push a new commit or call the API to run a new build`

Time to open the war chest? :P @geeknoid @ozevren

**Comment by geeknoid** [comment]
We're trying to fix CircleCi, it's a payment snafu...

**Comment by pitlv2109** [comment]
@geeknoid Any update on the billing issue?

**Comment by howardjohn** [comment]
should he fixed, I think you may need to send a new commit or something
though to trigger it

**Comment by pitlv2109** [comment]
It was fixed and then it happened again last Thursday, but I'll push a new commit to see if this has been resolved.

**Comment by pitlv2109** [comment]
`RetrieveData` is actually intended for testing only https://github.com/census-instrumentation/opencensus-go/blob/master/stats/view/worker.go#L97.
Close this PR.

**Pull request closed without merging**
